#' @title
#' Running the ongoing of a trial with TOP as a cohort is recruited in parallel
#'
#' @description
#' Given the dataset of patients \code{tableau} and \code{tableau_para} generated with the function
#' \code{\link{gen_patients_multinomTOP}} or with a similar structure. The function runs for 1 trial,
#' and given the data and the threshold, it simulates the ongoing of the trial and return the final result.
#' The TOP is a single-arm design. The code is from Ruitao Lin and was adapted to take into account the change
#' in the prior due to the parallel cohort.
#'
#' @return
#' A data.frame of 1 row containing the following informations:
#' \itemize{
#'   \item analyse: the index of interim analysis when the trial stopped;
#'   \item nb_pts: the number of patients at the end of the trial;
#'   \item temps_etude: the duration of the trial;
#'   \item decision: the decision at the end of the trial;
#'   \item arret_fut, arret_tox: 1 if the trial was stopped for futility/toxicity, 0 otherwise;
#'   \item nb_eff, nb_tox: number of responses/toxicities at the time of end of the trial;
#'   \item nb_eff_true, nb_tox_true: number of responses/toxicities at the time of end of the trial if all the patients had completed their observation window;
#'   \item C_, Gamma: the 2 tuning parameters of the threshold Cn;
#'   \item alphap_tox, betap_tox: the additionnal information given by the 2nd cohort;
#'   \item alpha_eff, beta_eff, alpha_tox, beta_tox: the 2 parameters of the beta distribution a posteriori for efficacy and toxicity at the end of the trial.
#' }
#'
#' @param ana_inter A vector of the supplementary patients recruited at each interim analysis compared with the previous one.
#' @param ana_inter_tox Vector of the number of additional patients at each interim analysis for toxicity. If analyses for effficacy and toxicity occur at the same
#' number of patients, set it to NULL.
#' @param tableau The dataset of the trial (generated by \code{\link{gen_patients_multinomTOP}} or with similar structure).
#' @param tableau_para The dataset of the parallel cohort (created within the function \code{\link{simu_essais_prior}}).
#' @param phitox Theoretical thresholds to compare values of efficacy and toxicity.
#' @param prior_eff,prior_tox The prior for efficacy and toxicity.
#' @param C_,gamm The 2 parameters of the threshold Cn.
#' @param interpatient Mean time between 2 patients.
#' @param max_teff,max_ttox Length of the observation window for efficacy and toxicity.
#'
#' @export
#'
#' @seealso \code{\link{gen_patients_multinomTOP}, \link{simu_essais_prior}}
realisation_essai_prior <- function(ana_inter,
                                    ana_inter_tox = NULL,
                                    tableau, tableau_para,
                                    phitox, prior_eff, prior_tox,
                                    C_, gamm,
                                    interpatient, max_teff, max_ttox) {

  if (!is.null(ana_inter_tox)) {
    ana_eff         <- cumsum(ana_inter)
    ana_tox         <- cumsum(ana_inter_tox)
    ana_inter_cum   <- sort(union(ana_eff, ana_tox))
    ana_inter       <- c(ana_inter_cum[1], diff(ana_inter_cum))
  } else {
    ana_eff         <- cumsum(ana_inter)
    ana_tox         <- cumsum(ana_inter)
    ana_inter_cum   <- cumsum(ana_inter)
    ana_inter       <- ana_inter
  }
  nmax <- sum(ana_inter)
  decision <- NULL

  for (i in ana_inter_cum) {

    if (i != nmax) {
      temps_decision <- tableau$temps_recrutement[i + 1] # Observation at the time when we would enroll the next patient
    } else {
      temps_decision <- max(tableau$temps_obseff[i], tableau$temps_obstox[i]) # Observation at the end of the trial if it goes that far
    }
    # Update the prior with the information given by the 2nd cohort
    if (nrow(tableau_para[tableau_para$temps_recrutement <= temps_decision, ]) == 0) {
      add_alpha_prior_tox <- 0
      add_beta_prior_tox <- 0
    } else {
      add_alpha_prior_tox <- sum(tableau_para$temps_tox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision)
      obs_tox_prior       <- (tableau_para$temps_tox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision) | (tableau_para$temps_obstox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision)
      suivi_tox_prior     <- (temps_decision - tableau_para$temps_arrivee[tableau_para$temps_recrutement <= temps_decision][!obs_tox_prior]) / max_ttox
      if (length(suivi_tox_prior) == 0)
        suivi_tox_prior   <- 0
      TESS_tox_prior      <- sum(obs_tox_prior) + sum(suivi_tox_prior)
      add_beta_prior_tox  <- TESS_tox_prior - add_alpha_prior_tox
    }
    obs_eff        <- (tableau$temps_eff[seq_len(i)] <= temps_decision) | (tableau$temps_obseff[seq_len(i)] <= temps_decision) # Boolean of observation of response criterion
    obs_tox        <- (tableau$temps_tox[seq_len(i)] <= temps_decision) | (tableau$temps_obstox[seq_len(i)] <= temps_decision) # Boolean of observation of toxicity criterion
    evt_eff        <- tableau$temps_eff[seq_len(i)] <= temps_decision # Boolean for response events
    evt_tox        <- tableau$temps_tox[seq_len(i)] <= temps_decision # Boolean for toxicity events
    yeff           <- sum(evt_eff) # Number of responses
    ytox           <- sum(evt_tox) # Number of toxicities
    PP_eff         <- pbeta(phitox[1], prior_eff + yeff, 1 - prior_eff + i - yeff)
    PP_tox         <- 1 - pbeta(phitox[2], prior_tox + add_alpha_prior_tox + ytox, 1 - prior_tox + add_beta_prior_tox + i - ytox)
    seuil          <- 1 - C_ * (i / sum(ana_inter)) ^ gamm
    addtime        <- 0


    if (i %in% ana_tox) {

      # Suspension rules: when not enough responses to be sure of efficacy or not enough toxicities to be sure about toxicity
      if (PP_tox <= seuil) { # Case where no stopping for toxicity

        if (PP_eff * (i %in% ana_eff) > seuil) { # Case where stopping for futility

          temps_decision_bis <- 0

          while ((1 - sum(obs_eff) / i >= i / nmax) || (1 - sum(obs_tox) / i >= i / nmax)) {
            # More than n / N pending patients so wait until enough non pending patients
            addtime <- addtime + interpatient
            temps_decision_bis <- temps_decision + addtime
            obs_eff <- (tableau$temps_eff[seq_len(i)] <= temps_decision_bis) | (tableau$temps_obseff[seq_len(i)] <= temps_decision_bis)
            obs_tox <- (tableau$temps_tox[seq_len(i)] <= temps_decision_bis) | (tableau$temps_obstox[seq_len(i)] <= temps_decision_bis)

          }

        } else { # Case where no stopping for futility

          while (1 - sum(obs_tox) / i >= i / nmax) {
            # More than n / N pending patientsfor toxicity so wait until enough non pending patients
            # We are here sure that if more responses occured we still won't stop for futility
            addtime <- addtime + interpatient
            temps_decision_bis <- temps_decision + addtime
            obs_tox <- (tableau$temps_tox[seq_len(i)] <= temps_decision_bis) | (tableau$temps_obstox[seq_len(i)] <= temps_decision_bis)

          }

        }

      }

    } else {

      if (PP_eff > seuil) {

        temps_decision_bis <- 0

        while (1 - sum(obs_eff) / i >= i / nmax) {
          # More than n / N pending patients so wait until enough non pending patients
          addtime <- addtime + interpatient
          temps_decision_bis <- temps_decision + addtime
          obs_eff <- (tableau$temps_eff[seq_len(i)] <= temps_decision_bis) | (tableau$temps_obseff[seq_len(i)] <= temps_decision_bis)

        }

      }

    }


    if (i != nmax) tableau[(i + 1):nmax, 10:14] <- tableau[(i + 1):nmax, 10:14] + addtime
    if (i != nmax) temps_decision <- tableau$temps_recrutement[i + 1]

    if (nrow(tableau_para[tableau_para$temps_recrutement <= temps_decision, ]) == 0) {
      add_alpha_prior_tox <- 0
      add_beta_prior_tox <- 0
    } else {
      add_alpha_prior_tox <- sum(tableau_para$temps_tox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision)
      obs_tox_prior       <- (tableau_para$temps_tox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision) | (tableau_para$temps_obstox[tableau_para$temps_recrutement <= temps_decision] <= temps_decision)
      suivi_tox_prior     <- (temps_decision - tableau_para$temps_arrivee[tableau_para$temps_recrutement <= temps_decision][!obs_tox_prior]) / max_ttox
      if (length(suivi_tox_prior) == 0)
        suivi_tox_prior   <- 0
      TESS_tox_prior      <- sum(obs_tox_prior) + sum(suivi_tox_prior)
      add_beta_prior_tox  <- TESS_tox_prior - add_alpha_prior_tox
    }

    obs_eff        <- (tableau$temps_eff[seq_len(i)] <= temps_decision) | (tableau$temps_obseff[seq_len(i)] <= temps_decision)
    obs_tox        <- (tableau$temps_tox[seq_len(i)] <= temps_decision) | (tableau$temps_obstox[seq_len(i)] <= temps_decision)
    evt_eff        <- tableau$temps_eff[seq_len(i)] <= temps_decision
    evt_tox        <- tableau$temps_tox[seq_len(i)] <= temps_decision
    yeff           <- sum(evt_eff)
    ytox           <- sum(evt_tox)
    suivi_eff      <- (temps_decision - tableau$temps_recrutement[seq_len(i)][!obs_eff]) / max_teff
    suivi_tox      <- (temps_decision - tableau$temps_recrutement[seq_len(i)][!obs_tox]) / max_ttox
    TESS_eff       <- sum(obs_eff) + sum(suivi_eff)
    TESS_tox       <- sum(obs_tox) + sum(suivi_tox)
    PP_eff         <- pbeta(phitox[1], prior_eff + yeff, 1 - prior_eff + TESS_eff - yeff)
    PP_tox         <- 1 - pbeta(phitox[2], prior_tox + add_alpha_prior_tox + ytox, 1 - prior_tox + add_beta_prior_tox + TESS_tox - ytox)

    if (PP_eff * (i %in% ana_eff) > seuil || PP_tox * (i %in% ana_tox) > seuil) {
      if (i == nmax) {decision <- "Stopping"} else {decision <- "Early stopping"}
      break
    }
    if (i == nmax) decision <- "Accept the treatment"

  }

  sortie <- data.frame(
    analyse     = match(i, ana_inter_cum),
    nb_pts      = i,
    temps_etude = temps_decision,
    decision    = decision,
    arret_fut   = as.numeric(PP_eff * (i %in% ana_eff) > seuil),
    arret_tox   = as.numeric(PP_tox * (i %in% ana_tox) > seuil),
    nb_eff      = yeff,
    nb_tox      = ytox,
    nb_eff_true = sum(tableau$eff[seq_len(i)]),
    nb_tox_true = sum(tableau$tox[seq_len(i)]),
    C_          = C_,
    Gamma       = gamm,
    alphap_tox  = add_alpha_prior_tox,
    betap_tox   = add_beta_prior_tox,
    alpha_eff   = prior_eff + yeff,
    beta_eff    = 1 - prior_eff + TESS_eff - yeff,
    alpha_tox   = prior_tox + ytox,
    beta_tox    = 1 - prior_tox + TESS_tox - ytox
  )

  return(sortie)

}


#' @title
#' Simulate single-arm trials with the TOP design
#'
#' @description
#' Either run the trials in \code{liste_tableaux} and give the results of all trials, or
#' simulate them and give the results. If \code{liste_tableaux} is NULL, you must supply the
#' arguments of the function \code{gen_patients_multinomTOP} to allow it to generate the data.
#'
#' @return
#'
#'
#' @param ana_inter A vector of the supplementary patients recruited at each interim analysis compared with the previous one.
#' @param ana_inter_tox Vector of the number of additional patients at each interim analysis for toxicity. If analyses for effficacy and toxicity occur at the same
#' number of patients, set it to NULL.
#' @param ana_par If liste_tableaux_par isn't given, the number of patients for the annex cohort.
#' @param liste_tableaux List of datasets or NULL if you want the function to generate them.
#' @param liste_tableaux_par List of datasets or NULL if you want the function to generate them (the annex cohort). By default, take \code{p_reel}
#' @param interpatient Mean time between 2 patients.
#' @param max_teff,max_ttox Length of the observation window for efficacy and toxicity.
#' @param seed_simu,seed_cut The seeds used to make reproducible the use of \code{rmultinom} (in the simulation of the trials'
#' datasets to determine the operating characteristics and to optimize the threshold Cn).
#' @param mat_beta_xi The link matrix between outcomes of the multinomial distribution and endpoints (careful, in the second row
#' 1 is actually for no toxicity /!\).
#' @param stock_matrice If TRUE, return the operating characteristics and the table of the decision in each trial, and
#' if FALSE, return only the operating characteristics.
#' @param alpha Maximal type I error rate desired.
#' @param bonf In case of multi-arm trial, TRUE indicates a Bonferroni correction to optimize Cn and FALSE no correction. For
#' now, TOP is onyl in single-arm so not useful yet.
#' @param nsim_oc,nsim_essai Number of simulated trials to optimize the threshold Cn and determine the operating characteristics.
#' @param p_n,p_a,p_reel Vectors of length 4 giving the multinomial law of probability for the unefficacy/toxicity hypothesis,
#' the efficacy/safety hypothesis and the simulated outcomes in the trials (\code{p_reel} = "real probabilities")
#' @param phi Theoretical thresholds to compare values of efficacy and toxicity.
#' @param prior The prior for efficacy and toxicity.
#' @param cut_seq,power_seq Vectors giving the screening values for both tuning parameters of Cn. If only 1 value supplied in each
#' argument, no grid search is performed and these values become the 2 optimized parameters.
#'
#' @export
#'
#' @examples
#' simu_essais_prior(alpha = .05,
#'                   ana_inter = c(30, 51),
#'                   ana_par = 9,
#'                   p_n = c(.1, .05, .15, .7),
#'                   p_a = c(.12, .18, .03, .67),
#'                   p_reel = c(.12, .18, .03, .67),
#'                   interpatient = 6,
#'                   max_teff = 180,
#'                   max_ttox = 180)
simu_essais_prior <- function(alpha = .1, bonf = FALSE,
                              nsim_oc = 10000, nsim_essai = 10000,
                              ana_inter, ana_inter_tox = NULL, ana_par,
                              p_n, p_a, p_reel,
                              liste_tableaux = NULL, liste_tableaux_par = NULL,
                              phi = NULL, prior = NULL,
                              cut_seq = seq(0.5, 0.95, by = 0.005),
                              power_seq = seq(0, 1, by = 0.01),
                              interpatient, max_teff, max_ttox,
                              seed_simu = 1993, seed_cut = 1024,
                              mat_beta_xi = matrix(c(1, 1, 0, 0, 0, 1, 0, 1), nrow = 2, byrow = TRUE),
                              stock_matrice = FALSE) {

  if (length(alpha) != 1 || !is.numeric(alpha) || alpha > 1 || alpha < 0)
    stop("Alpha risk should be defined as a real between 0 and 1.", call. = FALSE)
  if (alpha < 0.01 | alpha > 0.3)
    warning(paste0("Specified alpha risk is a bit extreme: ", alpha, "."), call. = FALSE, immediate. = TRUE)
  if (!is.matrix(mat_beta_xi) || any(dim(mat_beta_xi) != c(2, 4)))
    stop("mat_beta_xi should be a 2 by 4 matrix.", call. = FALSE)
  if (length(p_n) != 4)
    stop("\"p_n\" should be a vector of length 4 :\n1 = Pr(Eff & Tox), 2 = Pr(Eff & no Tox) 3 = Pr(no Eff & Tox) et 4 = Pr(no Eff & no Tox)", call. = FALSE)
  if (!dplyr::near(sum(p_n), 1))
    stop("\"p_n\" should sum to 1 as it it the law of probability.", call. = FALSE)
  if (length(p_reel) != 4)
    stop("\"p_reel\" should be a vector of length 4 :\n1 = Pr(Eff & Tox), 2 = Pr(Eff & no Tox) 3 = Pr(no Eff & Tox) et 4 = Pr(no Eff & no Tox)", call. = FALSE)
  if (!dplyr::near(sum(p_reel), 1))
    stop("\"p_reel\" should sum to 1 as it it the law of probability.", call. = FALSE)
  if (length(p_a) != 4)
    stop("\"p_a\" should be a vector of length 4 :\n1 = Pr(Eff & Tox), 2 = Pr(Eff & no Tox) 3 = Pr(no Eff & Tox) et 4 = Pr(no Eff & no Tox)", call. = FALSE)
  if (!dplyr::near(sum(p_a), 1))
    stop("\"p_a\" should sum to 1 as it it the law of probability.", call. = FALSE)
  if (nsim_oc < 0 | nsim_essai < 0 | any(ana_inter < 0))
    stop("nsim_oc, nsim_essai et ana_inter should be positive integers.", call. = FALSE)
  if (nsim_oc %% 1 != 0 | nsim_essai %% 1 != 0 | any(ana_inter %% 1 != 0))
    stop("nsim_oc, nsim_essai et ana_inter should be positive integers.", call. = FALSE)
  if (!is.null(prior)) {
    if (length(prior) != 4)
      stop("\"prior\" should be a vector of length 4:\n1 = Pr(Eff & Tox), 2 = Pr(Eff & no Tox) 3 = Pr(no Eff & Tox) et 4 = Pr(no Eff & no Tox).", call. = FALSE)
    if (!dplyr::near(sum(prior), 1))
      stop("\"prior\" should sum to 1.", call. = FALSE)
  } else {
    prior <- p_n
  }

  if (is.null(phi)) {
    phitox <- c(sum(p_n * mat_beta_xi[1, ]), 1 - sum(p_n * mat_beta_xi[2, ]))
    phi <- phitox
    phinotox <- c(sum(p_n * mat_beta_xi[1, ]), sum(p_n * mat_beta_xi[2, ]))
  } else {
    phitox <- phi
    phinotox <- c(phi[1], 1 - phi[2])
  }

  if (!is.numeric(cut_seq) | !is.numeric(power_seq))
    stop("\"cut_seq\" and \"power_seq\" should be of numeric type.", call. = FALSE)
  if (length(cut_seq) == 1 & length(power_seq) == 1) {
    C_ <- cut_seq
    gamm <- power_seq
  } else {
    carac_optimales <- suppressMessages(suppressWarnings(
      deter_cutoff(
        alpha         = alpha,
        bonf          = bonf,
        nsim_oc       = nsim_oc,
        ana_inter     = ana_inter,
        ana_inter_tox = ana_inter_tox,
        rand_ratio    = 1,
        mat_beta_xi   = mat_beta_xi,
        phi           = phinotox,
        p_n           = p_n,
        prior         = prior,
        p_a           = p_a,
        cut_seq       = cut_seq,
        power_seq     = power_seq,
        seed          = seed_cut,
        methode       = 3,
        affich_mat    = "No"
      )
    ))
    C_ <- carac_optimales[[1]]["C_"]
    gamm <- carac_optimales[[1]]["gamma"]
  }

  if (length(interpatient) != 1 || !is.numeric(interpatient) || interpatient <= 0)
    stop("\"interpatient\" should be an positive real.", call. = FALSE)
  if (length(max_teff) != 1 || !is.numeric(max_teff) || max_teff <= 0)
    stop("\"max_teff\" should be an positive real.", call. = FALSE)
  if (length(max_ttox) != 1 || !is.numeric(max_ttox) || max_ttox <= 0)
    stop("\"max_ttox\" should be an positive real.", call. = FALSE)
  if (length(ana_par) != 1 || !is.numeric(ana_par) || ana_par <= 0)
    stop("\"ana_par\" should be an positive real.", call. = FALSE)

  if (is.null(liste_tableaux)) {
    liste_tableaux <- gen_patients_multinomTOP(n_sim         = nsim_essai,
                                               ana_inter     = ana_inter,
                                               ana_inter_tox = ana_inter_tox,
                                               interpatient  = interpatient,
                                               max_teff      = max_teff,
                                               max_ttox      = max_ttox,
                                               multinom_ttt  = list(p_reel),
                                               mat_beta_xi   = mat_beta_xi,
                                               seed          = seed_simu)
  }

  if (is.null(liste_tableaux_par)) {
    set.seed(seed_simu)
    on.exit(expr = {set.seed(NULL)}, add = TRUE)
    liste_tableaux_par <- lapply(
      X = liste_tableaux,
      FUN = function(x) {
        res <- data.frame(temps_recrutement = sort(runif(ana_par, 0, max(x$temps_recrutement))))
        res$tox <- rbinom(ana_par, 1, 1 - sum(p_reel * mat_beta_xi[2, ]))
        res$temps_tox <- gen_temps_patient(n = ana_par, tmax = max_ttox)
        res$temps_tox <- ifelse(res$tox == 1, res$temps_arrivee + res$temps_tox, 1e+12)
        res$temps_obstox <- res$temps_arrivee + max_ttox
        return(res)
      }
    )
  }

  prior_eff <- sum(prior * mat_beta_xi[1, ])
  prior_tox <- 1 - sum(prior * mat_beta_xi[2, ])

  tab_essais <- purrr::map2_dfr(liste_tableaux,
                                liste_tableaux_par,
                                ~ realisation_essai_prior(ana_inter     = ana_inter,
                                                          ana_inter_tox = ana_inter_tox,
                                                          tableau       = .x,
                                                          tableau_para  = .y,
                                                          phitox        = phitox,
                                                          prior_eff     = prior_eff,
                                                          prior_tox     = prior_tox,
                                                          C_            = C_,
                                                          gamm          = gamm,
                                                          interpatient  = interpatient,
                                                          max_teff      = max_teff,
                                                          max_ttox      = max_ttox),
                                .id = "essai")

  if (stock_matrice) {
    return(list(
      op_char = c(rejet_h0 = mean(tab_essais$decision == "Accept the treatment"),
                  moy_pts = mean(tab_essais$nb_pts),
                  moy_duree = mean(tab_essais$temps_etude)),
      tab_essais = tab_essais
    ))
  } else {
    return(c(moy_pts = mean(tab_essais$nb_pts),
             moy_duree = mean(tab_essais$temps_etude),
             rejet_h0 = mean(tab_essais$decision == "Accept the treatment"),
             arret_prema = mean(grepl("Early", tab_essais$decision)),
             arret_fut = mean(tab_essais$arret_fut),
             arret_tox = mean(tab_essais$arret_tox),
             nb_eff = mean(tab_essais$nb_eff),
             nb_tox = mean(tab_essais$nb_tox)))
  }

}
