# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetDecision <- function(AnasInters, LambdaM, GammaM, Prior, Delta) {
    .Call('_multibrasBOP2_GetDecision', PACKAGE = 'multibrasBOP2', AnasInters, LambdaM, GammaM, Prior, Delta)
}

GetOCCnm <- function(MatPts, Prior, Phi, AnaEff, AnaTox, NbAna, LambdaM, GammaM, Decisions, Control = FALSE, Delta = 0L) {
    .Call('_multibrasBOP2_GetOCCnm', PACKAGE = 'multibrasBOP2', MatPts, Prior, Phi, AnaEff, AnaTox, NbAna, LambdaM, GammaM, Decisions, Control, Delta)
}

DeterCnm <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control = FALSE, Seed = 1024) {
    .Call('_multibrasBOP2_DeterCnm', PACKAGE = 'multibrasBOP2', Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control, Seed)
}

GetDecisionCnma <- function(AnasInters, NBras, LambdaH, GammaH, LambdaMono, Prior, Delta) {
    .Call('_multibrasBOP2_GetDecisionCnma', PACKAGE = 'multibrasBOP2', AnasInters, NBras, LambdaH, GammaH, LambdaMono, Prior, Delta)
}

GetOCCnma <- function(MatPts, Prior, Phi, AnaInter, AnaEff, AnaTox, NbAna, LambdaH, GammaH, LambdaMono, Decisions, Control = FALSE, Delta = 0L) {
    .Call('_multibrasBOP2_GetOCCnma', PACKAGE = 'multibrasBOP2', MatPts, Prior, Phi, AnaInter, AnaEff, AnaTox, NbAna, LambdaH, GammaH, LambdaMono, Decisions, Control, Delta)
}

DeterCnma <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control = FALSE, Seed = 1024) {
    .Call('_multibrasBOP2_DeterCnma', PACKAGE = 'multibrasBOP2', Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control, Seed)
}

GenPts <- function(NSim, AnaInter, Probs, Seed = 1024) {
    .Call('_multibrasBOP2_GenPts', PACKAGE = 'multibrasBOP2', NSim, AnaInter, Probs, Seed)
}

set_seed <- function(seed) {
    invisible(.Call('_multibrasBOP2_set_seed', PACKAGE = 'multibrasBOP2', seed))
}

rmultinom_1 <- function(size, probs, N) {
    .Call('_multibrasBOP2_rmultinom_1', PACKAGE = 'multibrasBOP2', size, probs, N)
}

rmultinom_rcpp <- function(n, size, probs) {
    .Call('_multibrasBOP2_rmultinom_rcpp', PACKAGE = 'multibrasBOP2', n, size, probs)
}

[[Rcpp::depends <- function([[Rcpp::depends(RcppNumerical) {
    .Call('_multibrasBOP2_[[Rcpp::depends', PACKAGE = 'multibrasBOP2', [[Rcpp::depends(RcppNumerical)
}

