# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call(`_multibrasBOP2_set_seed`, seed))
}

rmultinom_1 <- function(size, probs, N) {
    .Call(`_multibrasBOP2_rmultinom_1`, size, probs, N)
}

rmultinom_rcpp <- function(n, size, probs) {
    .Call(`_multibrasBOP2_rmultinom_rcpp`, n, size, probs)
}

GenPts <- function(NSim, AnaInter, Probs, Seed = 1024) {
    .Call(`_multibrasBOP2_GenPts`, NSim, AnaInter, Probs, Seed)
}

set_seed <- function(seed) {
    invisible(.Call(`_multibrasBOP2_set_seed`, seed))
}

rmultinom_1 <- function(size, probs, N) {
    .Call(`_multibrasBOP2_rmultinom_1`, size, probs, N)
}

rmultinom_rcpp <- function(n, size, probs) {
    .Call(`_multibrasBOP2_rmultinom_rcpp`, n, size, probs)
}

[[Rcpp::depends <- function([[Rcpp::depends(RcppNumerical) {
    .Call(`_multibrasBOP2_[[Rcpp::depends`, [[Rcpp::depends(RcppNumerical)
}

GenPts <- function(NSim, AnaInter, Probs, Seed = 1024) {
    .Call(`_multibrasBOP2_GenPts`, NSim, AnaInter, Probs, Seed)
}

[[Rcpp::depends <- function([[Rcpp::depends(RcppNumerical) {
    .Call(`_multibrasBOP2_[[Rcpp::depends`, [[Rcpp::depends(RcppNumerical)
}

GetDecision <- function(AnasInters, LambdaM, GammaM, Prior, Delta) {
    .Call(`_multibrasBOP2_GetDecision`, AnasInters, LambdaM, GammaM, Prior, Delta)
}

GetOCCnm <- function(MatPts, Prior, Phi, AnaEff, AnaTox, NbAna, LambdaM, GammaM, Decisions, Control = FALSE, Delta = 0L) {
    .Call(`_multibrasBOP2_GetOCCnm`, MatPts, Prior, Phi, AnaEff, AnaTox, NbAna, LambdaM, GammaM, Decisions, Control, Delta)
}

DeterCnm <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control = FALSE, Seed = 1024) {
    .Call(`_multibrasBOP2_DeterCnm`, Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control, Seed)
}

[[Rcpp::depends <- function([[Rcpp::depends(RcppNumerical) {
    .Call(`_multibrasBOP2_[[Rcpp::depends`, [[Rcpp::depends(RcppNumerical)
}

GetDecisionCnma <- function(AnasInters, NBras, LambdaH, GammaH, LambdaMono, Prior, Delta) {
    .Call(`_multibrasBOP2_GetDecisionCnma`, AnasInters, NBras, LambdaH, GammaH, LambdaMono, Prior, Delta)
}

GetOCCnma <- function(MatPts, Prior, Phi, AnaInter, AnaEff, AnaTox, NbAna, LambdaH, GammaH, LambdaMono, Decisions, Control = FALSE, Delta = 0L) {
    .Call(`_multibrasBOP2_GetOCCnma`, MatPts, Prior, Phi, AnaInter, AnaEff, AnaTox, NbAna, LambdaH, GammaH, LambdaMono, Decisions, Control, Delta)
}

DeterCnma <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control = FALSE, Seed = 1024) {
    .Call(`_multibrasBOP2_DeterCnma`, Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control, Seed)
}

