# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GenPts <- function(NSim, AnaInter, Probs, Seed = 1024) {
    .Call('_multibrasBOP2_GenPts', PACKAGE = 'multibrasBOP2', NSim, AnaInter, Probs, Seed)
}

DeterCnm <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control = FALSE, Seed = 1024) {
    .Call('_multibrasBOP2_DeterCnm', PACKAGE = 'multibrasBOP2', Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaMSeq, GammaMSeq, Control, Seed)
}

DeterCnma <- function(Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control = FALSE, Seed = 1024) {
    .Call('_multibrasBOP2_DeterCnma', PACKAGE = 'multibrasBOP2', Fwer, NBras, NSim, AnaInter, AnaEff, AnaTox, Prior, PN, PA, Phi, Delta, LambdaHSeq, GammaHSeq, LambdaMonoSeq, GammaMonoSeq, Control, Seed)
}

